
from __future__ import annotations

from itertools import product
from pathlib import Path

import numpy as np
import pandas as pd

from data import InteractionData
from ease import EASE

N_EASE_CAND = 50   # candidates generated by EASE (fusion may use fewer)


def load_recs(path: str | Path) -> dict[int, list[int]]:
    df = pd.read_csv(path)
    return {int(r.user_idx): [int(x) for x in r.items.split(",")]
            for r in df.itertuples()}


def best_ease_params() -> tuple[float | None, float]:
    """(half_life, l2) of the best row in the EASE sweep results."""
    sweep = pd.read_csv("results/ease_sweep.csv")
    row = sweep.loc[sweep["recall_at_10"].idxmax()]
    hl = None if pd.isna(row["half_life"]) else float(row["half_life"])
    return hl, float(row["l2"])


def best_variant_params() -> tuple[float, float]:
    """(pop_reg, l2) of the best EDLAE-style EASE in the variant sweep.

    Falls back to plain EASE (pop_reg=0) if the variant sweep hasn't been run.
    """
    path = Path("results/ease_variant_sweep.csv")
    if not path.exists():
        return 0.0, best_ease_params()[1]
    sweep = pd.read_csv(path)
    row = sweep.loc[sweep["recall_at_10"].idxmax()]
    return float(row["pop_reg"]), float(row["l2"])


def rrf_fuse(rankings: list[dict[int, list[int]]],
             weights: tuple[float, ...] | None = None,
             k: int = 10, rrf_k: float = 60.0,
             n_cand: int = 50) -> dict[int, list[int]]:
    if weights is None:
        weights = (1.0,) * len(rankings)
    users = set.intersection(*(set(r) for r in rankings))
    fused = {}
    for u in users:
        scores: dict[int, float] = {}
        for w, ranking in zip(weights, rankings):
            for rank, item in enumerate(ranking[u][:n_cand]):
                scores[item] = scores.get(item, 0.0) + w / (rrf_k + rank + 1)
        fused[u] = sorted(scores, key=lambda i: -scores[i])[:k]
    return fused


def main() -> None:
    data = InteractionData("data", val_frac=0.1)
    hl, _ = best_ease_params()
    pop_reg, l2 = best_variant_params()
    print(f"EDLAE-EASE params: half_life={hl}, lambda={l2}, pop_reg={pop_reg}",
          flush=True)

    tiger_val = load_recs("results/tiger_recs_val.csv")
    sasrec_val = load_recs("results/sasrec_recs_val.csv")
    users = np.array(sorted(set(tiger_val) & set(sasrec_val)))
    X = data.to_csr("train", half_life_days=hl)
    ease_val = EASE(l2, pop_reg=pop_reg).fit(X).recommend(X, users, k=N_EASE_CAND)
    rankings = [ease_val, tiger_val, sasrec_val]

    for name, recs in [("EDLAE-EASE", ease_val), ("TIGER", tiger_val),
                       ("SASRec", sasrec_val)]:
        r = data.recall_at_k(recs, k=10, users=users)
        print(f"{name:>10}  val Recall@10 = {r:.4f}", flush=True)

    # Grid over fusion hyperparameters; weights are (EASE, TIGER, SASRec).
    weight_grid = [(1, 1, 1), (2, 1, 1), (2, 2, 1), (3, 2, 1), (1, 2, 1),
                   (2, 3, 1), (3, 2, 2), (2, 1, 0), (1, 1, 0)]
    rrf_ks = [5.0, 10.0, 15.0, 20.0, 30.0, 60.0]
    n_cands = [10, 20, 30, 50]
    results: dict[tuple, float] = {}
    for weights, rrf_k, n_cand in product(weight_grid, rrf_ks, n_cands):
        fused = rrf_fuse(rankings, weights, rrf_k=rrf_k, n_cand=n_cand)
        results[(weights, rrf_k, n_cand)] = data.recall_at_k(
            fused, k=10, users=users)

    # Validation here is ~2k sparse-truth users, so the grid is noisy and the raw
    # argmax can be a single-cell spike. Select instead by each cell's score
    # smoothed over its (rrf_k, n_cand) neighbours -- the most robust basin.
    def smoothed(cfg: tuple) -> float:
        w, rk, nc = cfg
        i, j = rrf_ks.index(rk), n_cands.index(nc)
        vals = [results[(w, rrf_ks[ni], n_cands[nj])]
                for ni in (i - 1, i, i + 1) if 0 <= ni < len(rrf_ks)
                for nj in (j - 1, j, j + 1) if 0 <= nj < len(n_cands)]
        return sum(vals) / len(vals)

    # Only interior cells are eligible as the robust pick: edge cells have
    # truncated neighbourhoods, so their smoothed score isn't comparable (and an
    # edge spike would slip through).
    interior = [cfg for cfg in results
                if cfg[1] not in (rrf_ks[0], rrf_ks[-1])
                and cfg[2] not in (n_cands[0], n_cands[-1])]
    raw_cfg = max(results, key=results.get)
    robust_cfg = max(interior, key=smoothed)
    print("\ntop fusion configs by raw val Recall@10:", flush=True)
    for cfg in sorted(results, key=results.get, reverse=True)[:8]:
        w, rk, nc = cfg
        print(f"  w={w}  rrf_k={rk:>4.0f}  n_cand={nc:>2}"
              f"  raw={results[cfg]:.4f}  smoothed={smoothed(cfg):.4f}",
              flush=True)
    print(f"\nraw argmax : w={raw_cfg[0]} rrf_k={raw_cfg[1]:.0f} "
          f"n_cand={raw_cfg[2]}  R@10={results[raw_cfg]:.4f}", flush=True)
    print(f"robust pick: w={robust_cfg[0]} rrf_k={robust_cfg[1]:.0f} "
          f"n_cand={robust_cfg[2]}  R@10={results[robust_cfg]:.4f} "
          f"(smoothed {smoothed(robust_cfg):.4f})  <- submitted", flush=True)

    weights, rrf_k, n_cand = robust_cfg
    best_recall = results[robust_cfg]
    Path("results").mkdir(exist_ok=True)
    pd.DataFrame([{"model": "EDLAE-EASE+TIGER+SASRec",
                   "recall_at_10": best_recall, "weights": str(weights),
                   "rrf_k": rrf_k, "n_cand": n_cand, "selection": "smoothed",
                   "raw_recall_at_10": results[raw_cfg]}]).to_csv(
        "results/ensemble_val.csv", index=False)

    tiger_target = load_recs("results/tiger_recs_target.csv")
    sasrec_target = load_recs("results/sasrec_recs_target.csv")
    X_full = data.to_csr("full+test", half_life_days=hl)
    ease_target = EASE(l2, pop_reg=pop_reg).fit(X_full).recommend(
        X_full, data.target_user_idx, k=N_EASE_CAND)
    fused_target = rrf_fuse([ease_target, tiger_target, sasrec_target],
                            weights, rrf_k=rrf_k, n_cand=n_cand)
    path = data.write_submission(fused_target, "submission_ensemble.csv")
    print(f"wrote {path} (submitted fusion val Recall@10 = {best_recall:.4f})",
          flush=True)


if __name__ == "__main__":
    main()
